---
 apiVersion: v1
 kind: Pod
 metadata:
   name: skaffold-service
   labels:
     app: skaffold-service
 spec:
   containers:
     - name: skaffold-service
       image: sunil/skaffold-service
       ports:
         - containerPort: 8090

