apiVersion: v1
kind: Service
metadata:
  labels:
    app: skaffold-service
  name: skaffold-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: skaffold-service
  type: NodePort
