apiVersion: v1
kind: Service
metadata:
  labels:
    app: skaffold-app
  name: skaffold-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: skaffold-app
  type: NodePort
